//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.2.0
//     from Assets/Controls/piaMainControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PiaMainControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PiaMainControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""piaMainControls"",
    ""maps"": [
        {
            ""name"": ""MainMap"",
            ""id"": ""ef0b6ca8-6e20-4b0e-a517-6f4ca56a391c"",
            ""actions"": [
                {
                    ""name"": ""PlayerMovement"",
                    ""type"": ""Value"",
                    ""id"": ""63a39e3a-13df-4b6f-a4c1-944a68652f9b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PlaceTurret"",
                    ""type"": ""Button"",
                    ""id"": ""e7236be6-9ee8-4130-a09d-07dcefe9094c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""3ca870f8-e0f5-447e-94fc-e0bb54df27a1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""0226f31b-b4ef-4268-9bc1-b7623b5162c2"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerMovement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""a92da148-58fb-4103-b72e-7f611b801945"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardDefault"",
                    ""action"": ""PlayerMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""bac2fecc-bfe8-485e-b539-a0a6763f9a65"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardDefault"",
                    ""action"": ""PlayerMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""5df65820-505c-4746-b7c4-84a00250126d"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardDefault"",
                    ""action"": ""PlayerMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""1e50ec46-8c7b-4111-a712-1f323c8bb898"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardDefault"",
                    ""action"": ""PlayerMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""27fc52c8-61b0-4900-a50d-fa87f280b2a8"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardDefault"",
                    ""action"": ""PlaceTurret"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a22c1f5b-3671-4d9d-9b54-2139dc57c985"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardDefault"",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""KeyboardDefault"",
            ""bindingGroup"": ""KeyboardDefault"",
            ""devices"": []
        }
    ]
}");
        // MainMap
        m_MainMap = asset.FindActionMap("MainMap", throwIfNotFound: true);
        m_MainMap_PlayerMovement = m_MainMap.FindAction("PlayerMovement", throwIfNotFound: true);
        m_MainMap_PlaceTurret = m_MainMap.FindAction("PlaceTurret", throwIfNotFound: true);
        m_MainMap_Pause = m_MainMap.FindAction("Pause", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // MainMap
    private readonly InputActionMap m_MainMap;
    private IMainMapActions m_MainMapActionsCallbackInterface;
    private readonly InputAction m_MainMap_PlayerMovement;
    private readonly InputAction m_MainMap_PlaceTurret;
    private readonly InputAction m_MainMap_Pause;
    public struct MainMapActions
    {
        private @PiaMainControls m_Wrapper;
        public MainMapActions(@PiaMainControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @PlayerMovement => m_Wrapper.m_MainMap_PlayerMovement;
        public InputAction @PlaceTurret => m_Wrapper.m_MainMap_PlaceTurret;
        public InputAction @Pause => m_Wrapper.m_MainMap_Pause;
        public InputActionMap Get() { return m_Wrapper.m_MainMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MainMapActions set) { return set.Get(); }
        public void SetCallbacks(IMainMapActions instance)
        {
            if (m_Wrapper.m_MainMapActionsCallbackInterface != null)
            {
                @PlayerMovement.started -= m_Wrapper.m_MainMapActionsCallbackInterface.OnPlayerMovement;
                @PlayerMovement.performed -= m_Wrapper.m_MainMapActionsCallbackInterface.OnPlayerMovement;
                @PlayerMovement.canceled -= m_Wrapper.m_MainMapActionsCallbackInterface.OnPlayerMovement;
                @PlaceTurret.started -= m_Wrapper.m_MainMapActionsCallbackInterface.OnPlaceTurret;
                @PlaceTurret.performed -= m_Wrapper.m_MainMapActionsCallbackInterface.OnPlaceTurret;
                @PlaceTurret.canceled -= m_Wrapper.m_MainMapActionsCallbackInterface.OnPlaceTurret;
                @Pause.started -= m_Wrapper.m_MainMapActionsCallbackInterface.OnPause;
                @Pause.performed -= m_Wrapper.m_MainMapActionsCallbackInterface.OnPause;
                @Pause.canceled -= m_Wrapper.m_MainMapActionsCallbackInterface.OnPause;
            }
            m_Wrapper.m_MainMapActionsCallbackInterface = instance;
            if (instance != null)
            {
                @PlayerMovement.started += instance.OnPlayerMovement;
                @PlayerMovement.performed += instance.OnPlayerMovement;
                @PlayerMovement.canceled += instance.OnPlayerMovement;
                @PlaceTurret.started += instance.OnPlaceTurret;
                @PlaceTurret.performed += instance.OnPlaceTurret;
                @PlaceTurret.canceled += instance.OnPlaceTurret;
                @Pause.started += instance.OnPause;
                @Pause.performed += instance.OnPause;
                @Pause.canceled += instance.OnPause;
            }
        }
    }
    public MainMapActions @MainMap => new MainMapActions(this);
    private int m_KeyboardDefaultSchemeIndex = -1;
    public InputControlScheme KeyboardDefaultScheme
    {
        get
        {
            if (m_KeyboardDefaultSchemeIndex == -1) m_KeyboardDefaultSchemeIndex = asset.FindControlSchemeIndex("KeyboardDefault");
            return asset.controlSchemes[m_KeyboardDefaultSchemeIndex];
        }
    }
    public interface IMainMapActions
    {
        void OnPlayerMovement(InputAction.CallbackContext context);
        void OnPlaceTurret(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
    }
}
