//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Controls/piaMainControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PiaMainControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PiaMainControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""piaMainControls"",
    ""maps"": [
        {
            ""name"": ""MainMap"",
            ""id"": ""ef0b6ca8-6e20-4b0e-a517-6f4ca56a391c"",
            ""actions"": [
                {
                    ""name"": ""PlayerMovement"",
                    ""type"": ""Value"",
                    ""id"": ""63a39e3a-13df-4b6f-a4c1-944a68652f9b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PlaceTurret"",
                    ""type"": ""Value"",
                    ""id"": ""e7236be6-9ee8-4130-a09d-07dcefe9094c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""3ca870f8-e0f5-447e-94fc-e0bb54df27a1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Accept"",
                    ""type"": ""Button"",
                    ""id"": ""ccb8a203-413e-4e65-94b7-1a0edf665883"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectUp"",
                    ""type"": ""Button"",
                    ""id"": ""92d47901-6fcd-4965-906a-020aedaea9a4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectDown"",
                    ""type"": ""Button"",
                    ""id"": ""9777e3c5-9ef5-4b39-b21a-b7ec6080e11d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectLeft"",
                    ""type"": ""Button"",
                    ""id"": ""e91db998-8c80-455b-a409-af5f46727e08"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectRight"",
                    ""type"": ""Button"",
                    ""id"": ""266bd2e6-7ed4-4a44-b5c7-a73bb99657f7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Deny"",
                    ""type"": ""Button"",
                    ""id"": ""02328218-5495-4164-89a9-5223857b50d5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""0226f31b-b4ef-4268-9bc1-b7623b5162c2"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerMovement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""a92da148-58fb-4103-b72e-7f611b801945"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardDefault"",
                    ""action"": ""PlayerMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""bac2fecc-bfe8-485e-b539-a0a6763f9a65"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardDefault"",
                    ""action"": ""PlayerMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""5df65820-505c-4746-b7c4-84a00250126d"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardDefault"",
                    ""action"": ""PlayerMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""1e50ec46-8c7b-4111-a712-1f323c8bb898"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardDefault"",
                    ""action"": ""PlayerMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""43191b16-01dd-4042-8b85-5ed0e6cf6357"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerMovement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""4b7704d7-c06d-4e8d-ab1b-0e499f0e06ee"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardDefault"",
                    ""action"": ""PlayerMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""75a41351-49fa-46b8-bbc9-e304e6964fff"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardDefault"",
                    ""action"": ""PlayerMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""f9f8dbfd-7c8a-4f98-845d-e62c4046a048"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardDefault"",
                    ""action"": ""PlayerMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""645b73d1-89ff-4b12-b96b-a6092d7740ab"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardDefault"",
                    ""action"": ""PlayerMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""b1064493-9ea1-4d6f-ae52-c7cf79e8d331"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerMovement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""6b5a0b3a-f500-477b-8c63-02e22f8ec551"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardDefault"",
                    ""action"": ""PlayerMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""fe675f4a-317d-43cb-a208-bc7f2b4b7511"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardDefault"",
                    ""action"": ""PlayerMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""edd448b3-bd50-462d-baac-f17a295d83d5"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardDefault"",
                    ""action"": ""PlayerMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""66e6c214-351a-4ccc-934f-4d1e4c2fa012"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardDefault"",
                    ""action"": ""PlayerMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""79f3193b-a56b-474b-ae16-58adb5dfdcc6"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardDefault"",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0430a8ef-ef89-420d-a49e-4aeec30629ff"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""2a103e6d-58ea-4e19-9934-101d685a2b3a"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlaceTurret"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""be30e1f7-082a-4335-a06f-c130e758d720"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardDefault"",
                    ""action"": ""PlaceTurret"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""cef6acfc-b479-4078-ac8f-af36df1010a3"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardDefault"",
                    ""action"": ""PlaceTurret"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""354424a0-382d-4148-baf7-0606490534b4"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardDefault"",
                    ""action"": ""PlaceTurret"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""c447bc34-1ac8-4691-9b65-db6075d5993a"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardDefault"",
                    ""action"": ""PlaceTurret"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""4e6cad73-e4c2-4953-b1d4-88c62b47c013"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlaceTurret"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""15ff4151-243a-4c34-9d8b-df83fcea108d"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardDefault"",
                    ""action"": ""PlaceTurret"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""49a6942e-d740-4191-b495-63ac9d077e27"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardDefault"",
                    ""action"": ""PlaceTurret"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""1f997a41-366b-4938-a37b-7b32b1c7657e"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardDefault"",
                    ""action"": ""PlaceTurret"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""edcf1ec9-07bd-48e7-83d0-fad1776c1c3e"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardDefault"",
                    ""action"": ""PlaceTurret"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""f214a2da-ca31-4793-a90f-0668e2263929"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Accept"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""07532806-1297-4e80-abfd-3bc1105fbe66"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Accept"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""502016e5-a1a0-4a9b-a454-9cbf42a1bf2a"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""92d381ac-fa0e-4a32-a2ba-ad676d09d686"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d1576824-63e8-4e63-8671-d3979c3dbe9e"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b643e904-1301-4d55-98a9-c887a0525c86"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""76d61400-dbf7-4924-a62a-2f434fd48c7e"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6c263c1f-63fb-49f2-9298-6cb34f295367"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""38910beb-919b-45c8-980e-bdad62203a4d"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""18b29f5f-6ecd-485f-810a-a7db055352d0"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""22be25d8-252f-4218-a398-cc7643710a55"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""10109a2d-a024-4d1f-a345-8b27c126045a"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""15657073-e188-48d8-9fa2-095d674e3603"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c48f7316-4b79-4a50-9893-4ff17b3e7a0e"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e7739a8d-bb59-4b3a-8353-253e8ce65bad"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Deny"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0dea5938-8e93-4fb9-8565-85c8a2d34a0b"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Deny"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""KeyboardDefault"",
            ""bindingGroup"": ""KeyboardDefault"",
            ""devices"": []
        }
    ]
}");
        // MainMap
        m_MainMap = asset.FindActionMap("MainMap", throwIfNotFound: true);
        m_MainMap_PlayerMovement = m_MainMap.FindAction("PlayerMovement", throwIfNotFound: true);
        m_MainMap_PlaceTurret = m_MainMap.FindAction("PlaceTurret", throwIfNotFound: true);
        m_MainMap_Pause = m_MainMap.FindAction("Pause", throwIfNotFound: true);
        m_MainMap_Accept = m_MainMap.FindAction("Accept", throwIfNotFound: true);
        m_MainMap_SelectUp = m_MainMap.FindAction("SelectUp", throwIfNotFound: true);
        m_MainMap_SelectDown = m_MainMap.FindAction("SelectDown", throwIfNotFound: true);
        m_MainMap_SelectLeft = m_MainMap.FindAction("SelectLeft", throwIfNotFound: true);
        m_MainMap_SelectRight = m_MainMap.FindAction("SelectRight", throwIfNotFound: true);
        m_MainMap_Deny = m_MainMap.FindAction("Deny", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // MainMap
    private readonly InputActionMap m_MainMap;
    private IMainMapActions m_MainMapActionsCallbackInterface;
    private readonly InputAction m_MainMap_PlayerMovement;
    private readonly InputAction m_MainMap_PlaceTurret;
    private readonly InputAction m_MainMap_Pause;
    private readonly InputAction m_MainMap_Accept;
    private readonly InputAction m_MainMap_SelectUp;
    private readonly InputAction m_MainMap_SelectDown;
    private readonly InputAction m_MainMap_SelectLeft;
    private readonly InputAction m_MainMap_SelectRight;
    private readonly InputAction m_MainMap_Deny;
    public struct MainMapActions
    {
        private @PiaMainControls m_Wrapper;
        public MainMapActions(@PiaMainControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @PlayerMovement => m_Wrapper.m_MainMap_PlayerMovement;
        public InputAction @PlaceTurret => m_Wrapper.m_MainMap_PlaceTurret;
        public InputAction @Pause => m_Wrapper.m_MainMap_Pause;
        public InputAction @Accept => m_Wrapper.m_MainMap_Accept;
        public InputAction @SelectUp => m_Wrapper.m_MainMap_SelectUp;
        public InputAction @SelectDown => m_Wrapper.m_MainMap_SelectDown;
        public InputAction @SelectLeft => m_Wrapper.m_MainMap_SelectLeft;
        public InputAction @SelectRight => m_Wrapper.m_MainMap_SelectRight;
        public InputAction @Deny => m_Wrapper.m_MainMap_Deny;
        public InputActionMap Get() { return m_Wrapper.m_MainMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MainMapActions set) { return set.Get(); }
        public void SetCallbacks(IMainMapActions instance)
        {
            if (m_Wrapper.m_MainMapActionsCallbackInterface != null)
            {
                @PlayerMovement.started -= m_Wrapper.m_MainMapActionsCallbackInterface.OnPlayerMovement;
                @PlayerMovement.performed -= m_Wrapper.m_MainMapActionsCallbackInterface.OnPlayerMovement;
                @PlayerMovement.canceled -= m_Wrapper.m_MainMapActionsCallbackInterface.OnPlayerMovement;
                @PlaceTurret.started -= m_Wrapper.m_MainMapActionsCallbackInterface.OnPlaceTurret;
                @PlaceTurret.performed -= m_Wrapper.m_MainMapActionsCallbackInterface.OnPlaceTurret;
                @PlaceTurret.canceled -= m_Wrapper.m_MainMapActionsCallbackInterface.OnPlaceTurret;
                @Pause.started -= m_Wrapper.m_MainMapActionsCallbackInterface.OnPause;
                @Pause.performed -= m_Wrapper.m_MainMapActionsCallbackInterface.OnPause;
                @Pause.canceled -= m_Wrapper.m_MainMapActionsCallbackInterface.OnPause;
                @Accept.started -= m_Wrapper.m_MainMapActionsCallbackInterface.OnAccept;
                @Accept.performed -= m_Wrapper.m_MainMapActionsCallbackInterface.OnAccept;
                @Accept.canceled -= m_Wrapper.m_MainMapActionsCallbackInterface.OnAccept;
                @SelectUp.started -= m_Wrapper.m_MainMapActionsCallbackInterface.OnSelectUp;
                @SelectUp.performed -= m_Wrapper.m_MainMapActionsCallbackInterface.OnSelectUp;
                @SelectUp.canceled -= m_Wrapper.m_MainMapActionsCallbackInterface.OnSelectUp;
                @SelectDown.started -= m_Wrapper.m_MainMapActionsCallbackInterface.OnSelectDown;
                @SelectDown.performed -= m_Wrapper.m_MainMapActionsCallbackInterface.OnSelectDown;
                @SelectDown.canceled -= m_Wrapper.m_MainMapActionsCallbackInterface.OnSelectDown;
                @SelectLeft.started -= m_Wrapper.m_MainMapActionsCallbackInterface.OnSelectLeft;
                @SelectLeft.performed -= m_Wrapper.m_MainMapActionsCallbackInterface.OnSelectLeft;
                @SelectLeft.canceled -= m_Wrapper.m_MainMapActionsCallbackInterface.OnSelectLeft;
                @SelectRight.started -= m_Wrapper.m_MainMapActionsCallbackInterface.OnSelectRight;
                @SelectRight.performed -= m_Wrapper.m_MainMapActionsCallbackInterface.OnSelectRight;
                @SelectRight.canceled -= m_Wrapper.m_MainMapActionsCallbackInterface.OnSelectRight;
                @Deny.started -= m_Wrapper.m_MainMapActionsCallbackInterface.OnDeny;
                @Deny.performed -= m_Wrapper.m_MainMapActionsCallbackInterface.OnDeny;
                @Deny.canceled -= m_Wrapper.m_MainMapActionsCallbackInterface.OnDeny;
            }
            m_Wrapper.m_MainMapActionsCallbackInterface = instance;
            if (instance != null)
            {
                @PlayerMovement.started += instance.OnPlayerMovement;
                @PlayerMovement.performed += instance.OnPlayerMovement;
                @PlayerMovement.canceled += instance.OnPlayerMovement;
                @PlaceTurret.started += instance.OnPlaceTurret;
                @PlaceTurret.performed += instance.OnPlaceTurret;
                @PlaceTurret.canceled += instance.OnPlaceTurret;
                @Pause.started += instance.OnPause;
                @Pause.performed += instance.OnPause;
                @Pause.canceled += instance.OnPause;
                @Accept.started += instance.OnAccept;
                @Accept.performed += instance.OnAccept;
                @Accept.canceled += instance.OnAccept;
                @SelectUp.started += instance.OnSelectUp;
                @SelectUp.performed += instance.OnSelectUp;
                @SelectUp.canceled += instance.OnSelectUp;
                @SelectDown.started += instance.OnSelectDown;
                @SelectDown.performed += instance.OnSelectDown;
                @SelectDown.canceled += instance.OnSelectDown;
                @SelectLeft.started += instance.OnSelectLeft;
                @SelectLeft.performed += instance.OnSelectLeft;
                @SelectLeft.canceled += instance.OnSelectLeft;
                @SelectRight.started += instance.OnSelectRight;
                @SelectRight.performed += instance.OnSelectRight;
                @SelectRight.canceled += instance.OnSelectRight;
                @Deny.started += instance.OnDeny;
                @Deny.performed += instance.OnDeny;
                @Deny.canceled += instance.OnDeny;
            }
        }
    }
    public MainMapActions @MainMap => new MainMapActions(this);
    private int m_KeyboardDefaultSchemeIndex = -1;
    public InputControlScheme KeyboardDefaultScheme
    {
        get
        {
            if (m_KeyboardDefaultSchemeIndex == -1) m_KeyboardDefaultSchemeIndex = asset.FindControlSchemeIndex("KeyboardDefault");
            return asset.controlSchemes[m_KeyboardDefaultSchemeIndex];
        }
    }
    public interface IMainMapActions
    {
        void OnPlayerMovement(InputAction.CallbackContext context);
        void OnPlaceTurret(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnAccept(InputAction.CallbackContext context);
        void OnSelectUp(InputAction.CallbackContext context);
        void OnSelectDown(InputAction.CallbackContext context);
        void OnSelectLeft(InputAction.CallbackContext context);
        void OnSelectRight(InputAction.CallbackContext context);
        void OnDeny(InputAction.CallbackContext context);
    }
}
